package theme

// Palette data derived from iTerm2-Color-Schemes (MIT):
// https://github.com/mbadolato/iTerm2-Color-Schemes.
// The original import generator is preserved at ruby-final-2026-08-04; future
// palette refreshes should add a Go generator before replacing this table.

var generatedThemes = map[string]map[Slot]string{
	"ayu": {
		"tab_active":           "bold #000000 on-#409fff",
		"tab_inactive":         "#82827f",
		"tab_agenda":           "#95e6cb",
		"tab_next":             "#aad94c",
		"tab_quadrants":        "#ffb454",
		"tab_inbox":            "#cda1fa",
		"tab_projects":         "#59c2ff",
		"tab_agenda_active":    "bold #95e6cb on-#409fff",
		"tab_next_active":      "bold #aad94c on-#409fff",
		"tab_quadrants_active": "bold #ffb454 on-#409fff",
		"tab_inbox_active":     "bold #cda1fa on-#409fff",
		"tab_projects_active":  "bold #59c2ff on-#409fff",
		"selection":            "#000000 on-#409fff",
		"accent":               "#95e6cb",
		"prompt":               "bold #95e6cb",
		"section":              "bold #bfbdb6",
		"approval_section":     "bold #ffb454",
		"inbox_section":        "bold #cda1fa",
		"modal_title":          "bold #000000 on-#409fff",
		"border":               "#686868",
		"border_gradient":      "#59c2ff #cda1fa @45",
		"form_group_label":     "bold #000000 on-#95e6cb",
		"context":              "bold #90e1c6",
		"context_selected":     "bold #90e1c6",
		"project":              "#cda1fa",
		"project_selected":     "bold #cda1fa",
		"title_selected":       "bold",
		"priority":             "bold #ffb454",
		"priority_selected":    "bold #ffb454",
		"muted":                "#82827f",
		"muted_selected":       "#82827f",
		"note":                 "#8f8e8b",
		"description":          "#8f8e8b",
		"link":                 "underline #59c2ff",
		"detail_label":         "bold #868683",
		"link_system":          "#95e6cb",
		"error":                "#f07178",
		"warning":              "#ffb454",
		"due_overdue":          "#f07178",
		"due_soon":             "#ffb454",
		"due_week":             "#95e6cb",
		"due_far":              "#686868",
		"due_overdue_selected": "bold #f07178",
		"due_soon_selected":    "bold #ffb454",
		"due_week_selected":    "bold #95e6cb",
		"due_far_selected":     "#686868",
		"state_next":           "#95e6cb",
		"state_waiting":        "#ffb454",
		"state_done":           "#686868",
		"outline_thread":       "#686868",
	},
	"ayu-light": {
		"tab_active":           "bold #ffffff on-#035bd6",
		"tab_inactive":         "#646667",
		"tab_agenda":           "#4cbf99",
		"tab_next":             "#86b300",
		"tab_quadrants":        "#f2ae49",
		"tab_inbox":            "#9e75c7",
		"tab_projects":         "#399ee6",
		"tab_agenda_active":    "bold #4cbf99 on-#035bd6",
		"tab_next_active":      "bold #86b300 on-#035bd6",
		"tab_quadrants_active": "bold #f2ae49 on-#035bd6",
		"tab_inbox_active":     "bold #9e75c7 on-#035bd6",
		"tab_projects_active":  "bold #399ee6 on-#035bd6",
		"selection":            "#ffffff on-#035bd6",
		"accent":               "#4cbf99",
		"prompt":               "bold #4cbf99",
		"section":              "bold #5c6166",
		"approval_section":     "bold #f2ae49",
		"inbox_section":        "bold #9e75c7",
		"modal_title":          "bold #ffffff on-#035bd6",
		"border":               "#686868",
		"border_gradient":      "#399ee6 #9e75c7 @45",
		"form_group_label":     "bold #000000 on-#4cbf99",
		"context":              "bold #46ba94",
		"context_selected":     "bold #46ba94",
		"project":              "#9e75c7",
		"project_selected":     "bold #9e75c7",
		"title_selected":       "bold",
		"priority":             "bold #f2ae49",
		"priority_selected":    "bold #f2ae49",
		"muted":                "#646667",
		"muted_selected":       "#646667",
		"note":                 "#636567",
		"description":          "#636567",
		"link":                 "underline #399ee6",
		"detail_label":         "bold #646667",
		"link_system":          "#4cbf99",
		"error":                "#f07171",
		"warning":              "#f2ae49",
		"due_overdue":          "#f07171",
		"due_soon":             "#f2ae49",
		"due_week":             "#4cbf99",
		"due_far":              "#686868",
		"due_overdue_selected": "bold #f07171",
		"due_soon_selected":    "bold #f2ae49",
		"due_week_selected":    "bold #4cbf99",
		"due_far_selected":     "#686868",
		"state_next":           "#4cbf99",
		"state_waiting":        "#f2ae49",
		"state_done":           "#686868",
		"outline_thread":       "#686868",
	},
	"ayu-mirage": {
		"tab_active":           "bold #000000 on-#409fff",
		"tab_inactive":         "#868583",
		"tab_agenda":           "#95e6cb",
		"tab_next":             "#d5ff80",
		"tab_quadrants":        "#ffd173",
		"tab_inbox":            "#dabafa",
		"tab_projects":         "#73d0ff",
		"tab_agenda_active":    "bold #95e6cb on-#409fff",
		"tab_next_active":      "bold #d5ff80 on-#409fff",
		"tab_quadrants_active": "bold #ffd173 on-#409fff",
		"tab_inbox_active":     "bold #dabafa on-#409fff",
		"tab_projects_active":  "bold #73d0ff on-#409fff",
		"selection":            "#000000 on-#409fff",
		"accent":               "#95e6cb",
		"prompt":               "bold #95e6cb",
		"section":              "bold #cccac2",
		"approval_section":     "bold #ffd173",
		"inbox_section":        "bold #dabafa",
		"modal_title":          "bold #000000 on-#409fff",
		"border":               "#686868",
		"border_gradient":      "#73d0ff #dabafa @45",
		"form_group_label":     "bold #000000 on-#95e6cb",
		"context":              "bold #90e1c6",
		"context_selected":     "bold #90e1c6",
		"project":              "#dabafa",
		"project_selected":     "bold #dabafa",
		"title_selected":       "bold",
		"priority":             "bold #ffd173",
		"priority_selected":    "bold #ffd173",
		"muted":                "#868583",
		"muted_selected":       "#868583",
		"note":                 "#959490",
		"description":          "#959490",
		"link":                 "underline #73d0ff",
		"detail_label":         "bold #8b8a88",
		"link_system":          "#95e6cb",
		"error":                "#f28779",
		"warning":              "#ffd173",
		"due_overdue":          "#f28779",
		"due_soon":             "#ffd173",
		"due_week":             "#95e6cb",
		"due_far":              "#686868",
		"due_overdue_selected": "bold #f28779",
		"due_soon_selected":    "bold #ffd173",
		"due_week_selected":    "bold #95e6cb",
		"due_far_selected":     "#686868",
		"state_next":           "#95e6cb",
		"state_waiting":        "#ffd173",
		"state_done":           "#686868",
		"outline_thread":       "#686868",
	},
	"catppuccin-frappe": {
		"tab_active":           "bold #000000 on-#f2d5cf",
		"tab_inactive":         "#8087a3",
		"tab_agenda":           "#98d2ca",
		"tab_next":             "#b9dba2",
		"tab_quadrants":        "#ecd7ae",
		"tab_inbox":            "#f4b8e4",
		"tab_projects":         "#adc2f3",
		"tab_agenda_active":    "bold #98d2ca on-#f2d5cf",
		"tab_next_active":      "bold #b9dba2 on-#f2d5cf",
		"tab_quadrants_active": "bold #ecd7ae on-#f2d5cf",
		"tab_inbox_active":     "bold #f4b8e4 on-#f2d5cf",
		"tab_projects_active":  "bold #adc2f3 on-#f2d5cf",
		"selection":            "#000000 on-#f2d5cf",
		"accent":               "#98d2ca",
		"prompt":               "bold #98d2ca",
		"section":              "bold #c6d0f5",
		"approval_section":     "bold #ecd7ae",
		"inbox_section":        "bold #f4b8e4",
		"modal_title":          "bold #000000 on-#f2d5cf",
		"border":               "#626880",
		"border_gradient":      "#adc2f3 #f4b8e4 @45",
		"form_group_label":     "bold #000000 on-#98d2ca",
		"context":              "bold #81c8be",
		"context_selected":     "bold #81c8be",
		"project":              "#f4b8e4",
		"project_selected":     "bold #f4b8e4",
		"title_selected":       "bold",
		"priority":             "bold #ecd7ae",
		"priority_selected":    "bold #ecd7ae",
		"muted":                "#8087a3",
		"muted_selected":       "#8087a3",
		"note":                 "#8f97b5",
		"description":          "#8f97b5",
		"link":                 "underline #adc2f3",
		"detail_label":         "bold #858ca9",
		"link_system":          "#98d2ca",
		"error":                "#eda0a2",
		"warning":              "#ecd7ae",
		"due_overdue":          "#eda0a2",
		"due_soon":             "#ecd7ae",
		"due_week":             "#98d2ca",
		"due_far":              "#626880",
		"due_overdue_selected": "bold #eda0a2",
		"due_soon_selected":    "bold #ecd7ae",
		"due_week_selected":    "bold #98d2ca",
		"due_far_selected":     "#626880",
		"state_next":           "#98d2ca",
		"state_waiting":        "#ecd7ae",
		"state_done":           "#626880",
		"outline_thread":       "#626880",
	},
	"catppuccin-latte": {
		"tab_active":           "bold #000000 on-#dc8a78",
		"tab_inactive":         "#8f93a4",
		"tab_agenda":           "#19a1a8",
		"tab_next":             "#46b02f",
		"tab_quadrants":        "#e49931",
		"tab_inbox":            "#ea76cb",
		"tab_projects":         "#3878f6",
		"tab_agenda_active":    "bold #19a1a8 on-#dc8a78",
		"tab_next_active":      "bold #46b02f on-#dc8a78",
		"tab_quadrants_active": "bold #e49931 on-#dc8a78",
		"tab_inbox_active":     "bold #ea76cb on-#dc8a78",
		"tab_projects_active":  "bold #3878f6 on-#dc8a78",
		"selection":            "#000000 on-#dc8a78",
		"accent":               "#19a1a8",
		"prompt":               "bold #19a1a8",
		"section":              "bold #4c4f69",
		"approval_section":     "bold #e49931",
		"inbox_section":        "bold #ea76cb",
		"modal_title":          "bold #000000 on-#dc8a78",
		"border":               "#acb0be",
		"border_gradient":      "#3878f6 #ea76cb @45",
		"form_group_label":     "bold #000000 on-#19a1a8",
		"context":              "bold #179299",
		"context_selected":     "bold #179299",
		"project":              "#ea76cb",
		"project_selected":     "bold #ea76cb",
		"title_selected":       "bold",
		"priority":             "bold #e49931",
		"priority_selected":    "bold #e49931",
		"muted":                "#8f93a4",
		"muted_selected":       "#8f93a4",
		"note":                 "#818498",
		"description":          "#818498",
		"link":                 "underline #3878f6",
		"detail_label":         "bold #8a8ea0",
		"link_system":          "#19a1a8",
		"error":                "#e7103f",
		"warning":              "#e49931",
		"due_overdue":          "#e7103f",
		"due_soon":             "#e49931",
		"due_week":             "#19a1a8",
		"due_far":              "#acb0be",
		"due_overdue_selected": "bold #e7103f",
		"due_soon_selected":    "bold #e49931",
		"due_week_selected":    "bold #19a1a8",
		"due_far_selected":     "#acb0be",
		"state_next":           "#19a1a8",
		"state_waiting":        "#e49931",
		"state_done":           "#acb0be",
		"outline_thread":       "#acb0be",
	},
	"catppuccin-macchiato": {
		"tab_active":           "bold #000000 on-#f4dbd6",
		"tab_inactive":         "#7c829e",
		"tab_agenda":           "#a5ded6",
		"tab_next":             "#bde3b0",
		"tab_quadrants":        "#f4e3c1",
		"tab_inbox":            "#f5bde6",
		"tab_projects":         "#adc5f7",
		"tab_agenda_active":    "bold #a5ded6 on-#f4dbd6",
		"tab_next_active":      "bold #bde3b0 on-#f4dbd6",
		"tab_quadrants_active": "bold #f4e3c1 on-#f4dbd6",
		"tab_inbox_active":     "bold #f5bde6 on-#f4dbd6",
		"tab_projects_active":  "bold #adc5f7 on-#f4dbd6",
		"selection":            "#000000 on-#f4dbd6",
		"accent":               "#a5ded6",
		"prompt":               "bold #a5ded6",
		"section":              "bold #cad3f5",
		"approval_section":     "bold #f4e3c1",
		"inbox_section":        "bold #f5bde6",
		"modal_title":          "bold #000000 on-#f4dbd6",
		"border":               "#5b6078",
		"border_gradient":      "#adc5f7 #f5bde6 @45",
		"form_group_label":     "bold #000000 on-#a5ded6",
		"context":              "bold #8bd5ca",
		"context_selected":     "bold #8bd5ca",
		"project":              "#f5bde6",
		"project_selected":     "bold #f5bde6",
		"title_selected":       "bold",
		"priority":             "bold #f4e3c1",
		"priority_selected":    "bold #f4e3c1",
		"muted":                "#7c829e",
		"muted_selected":       "#7c829e",
		"note":                 "#8d94b0",
		"description":          "#8d94b0",
		"link":                 "underline #adc5f7",
		"detail_label":         "bold #8288a4",
		"link_system":          "#a5ded6",
		"error":                "#f2a7b2",
		"warning":              "#f4e3c1",
		"due_overdue":          "#f2a7b2",
		"due_soon":             "#f4e3c1",
		"due_week":             "#a5ded6",
		"due_far":              "#5b6078",
		"due_overdue_selected": "bold #f2a7b2",
		"due_soon_selected":    "bold #f4e3c1",
		"due_week_selected":    "bold #a5ded6",
		"due_far_selected":     "#5b6078",
		"state_next":           "#a5ded6",
		"state_waiting":        "#f4e3c1",
		"state_done":           "#5b6078",
		"outline_thread":       "#5b6078",
	},
	"catppuccin-mocha": {
		"tab_active":           "bold #000000 on-#f5e0dc",
		"tab_inactive":         "#7b8098",
		"tab_agenda":           "#b1eae1",
		"tab_next":             "#c2ecbf",
		"tab_quadrants":        "#fcd682",
		"tab_inbox":            "#f5c2e7",
		"tab_projects":         "#aeccfc",
		"tab_agenda_active":    "bold #b1eae1 on-#f5e0dc",
		"tab_next_active":      "bold #c2ecbf on-#f5e0dc",
		"tab_quadrants_active": "bold #fcd682 on-#f5e0dc",
		"tab_inbox_active":     "bold #f5c2e7 on-#f5e0dc",
		"tab_projects_active":  "bold #aeccfc on-#f5e0dc",
		"selection":            "#000000 on-#f5e0dc",
		"accent":               "#b1eae1",
		"prompt":               "bold #b1eae1",
		"section":              "bold #cdd6f4",
		"approval_section":     "bold #fcd682",
		"inbox_section":        "bold #f5c2e7",
		"modal_title":          "bold #000000 on-#f5e0dc",
		"border":               "#585b70",
		"border_gradient":      "#aeccfc #f5c2e7 @45",
		"form_group_label":     "bold #000000 on-#b1eae1",
		"context":              "bold #94e2d5",
		"context_selected":     "bold #94e2d5",
		"project":              "#f5c2e7",
		"project_selected":     "bold #f5c2e7",
		"title_selected":       "bold",
		"priority":             "bold #fcd682",
		"priority_selected":    "bold #fcd682",
		"muted":                "#7b8098",
		"muted_selected":       "#7b8098",
		"note":                 "#8d92ab",
		"description":          "#8d92ab",
		"link":                 "underline #aeccfc",
		"detail_label":         "bold #81869e",
		"link_system":          "#b1eae1",
		"error":                "#f7aec2",
		"warning":              "#fcd682",
		"due_overdue":          "#f7aec2",
		"due_soon":             "#fcd682",
		"due_week":             "#b1eae1",
		"due_far":              "#585b70",
		"due_overdue_selected": "bold #f7aec2",
		"due_soon_selected":    "bold #fcd682",
		"due_week_selected":    "bold #b1eae1",
		"due_far_selected":     "#585b70",
		"state_next":           "#b1eae1",
		"state_waiting":        "#fcd682",
		"state_done":           "#585b70",
		"outline_thread":       "#585b70",
	},
	"dracula": {
		"tab_active":           "bold #ffffff on-#44475a",
		"tab_inactive":         "#8f9abb",
		"tab_agenda":           "#a4ffff",
		"tab_next":             "#69ff94",
		"tab_quadrants":        "#ffffa5",
		"tab_inbox":            "#ff79c6",
		"tab_projects":         "#d6acff",
		"tab_agenda_active":    "bold #a4ffff on-#44475a",
		"tab_next_active":      "bold #69ff94 on-#44475a",
		"tab_quadrants_active": "bold #ffffa5 on-#44475a",
		"tab_inbox_active":     "bold #ff79c6 on-#44475a",
		"tab_projects_active":  "bold #d6acff on-#44475a",
		"selection":            "#ffffff on-#44475a",
		"accent":               "#a4ffff",
		"prompt":               "bold #a4ffff",
		"section":              "bold #f8f8f2",
		"approval_section":     "bold #ffffa5",
		"inbox_section":        "bold #ff79c6",
		"modal_title":          "bold #ffffff on-#44475a",
		"border":               "#6272a4",
		"border_gradient":      "#d6acff #ff79c6 @45",
		"form_group_label":     "bold #000000 on-#a4ffff",
		"context":              "bold #8be9fd",
		"context_selected":     "bold #8be9fd",
		"project":              "#ff79c6",
		"project_selected":     "bold #ff79c6",
		"title_selected":       "bold",
		"priority":             "bold #ffffa5",
		"priority_selected":    "bold #ffffa5",
		"muted":                "#8f9abb",
		"muted_selected":       "#8f9abb",
		"note":                 "#a6aec7",
		"description":          "#a6aec7",
		"link":                 "underline #d6acff",
		"detail_label":         "bold #96a1bf",
		"link_system":          "#a4ffff",
		"error":                "#ff6e6e",
		"warning":              "#ffffa5",
		"due_overdue":          "#ff6e6e",
		"due_soon":             "#ffffa5",
		"due_week":             "#a4ffff",
		"due_far":              "#6272a4",
		"due_overdue_selected": "bold #ff6e6e",
		"due_soon_selected":    "bold #ffffa5",
		"due_week_selected":    "bold #a4ffff",
		"due_far_selected":     "#6272a4",
		"state_next":           "#a4ffff",
		"state_waiting":        "#ffffa5",
		"state_done":           "#6272a4",
		"outline_thread":       "#6272a4",
	},
	"everforest-dark-hard": {
		"tab_active":           "bold #ffffff on-#4c3743",
		"tab_inactive":         "#b4b7a3",
		"tab_agenda":           "#35a77c",
		"tab_next":             "#8da101",
		"tab_quadrants":        "#dfa000",
		"tab_inbox":            "#d699b6",
		"tab_projects":         "#3a94c5",
		"tab_agenda_active":    "bold #35a77c on-#4c3743",
		"tab_next_active":      "bold #8da101 on-#4c3743",
		"tab_quadrants_active": "bold #dfa000 on-#4c3743",
		"tab_inbox_active":     "bold #d699b6 on-#4c3743",
		"tab_projects_active":  "bold #3a94c5 on-#4c3743",
		"selection":            "#ffffff on-#4c3743",
		"accent":               "#35a77c",
		"prompt":               "bold #35a77c",
		"section":              "bold #d3c6aa",
		"approval_section":     "bold #dfa000",
		"inbox_section":        "bold #d699b6",
		"modal_title":          "bold #ffffff on-#4c3743",
		"border":               "#a6b0a0",
		"border_gradient":      "#3a94c5 #d699b6 @45",
		"form_group_label":     "bold #000000 on-#35a77c",
		"context":              "bold #83c092",
		"context_selected":     "bold #83c092",
		"project":              "#d699b6",
		"project_selected":     "bold #d699b6",
		"title_selected":       "bold",
		"priority":             "bold #dfa000",
		"priority_selected":    "bold #dfa000",
		"muted":                "#b4b7a3",
		"muted_selected":       "#b4b7a3",
		"note":                 "#babaa4",
		"description":          "#babaa4",
		"link":                 "underline #3a94c5",
		"detail_label":         "bold #b6b8a4",
		"link_system":          "#35a77c",
		"error":                "#f85552",
		"warning":              "#dfa000",
		"due_overdue":          "#f85552",
		"due_soon":             "#dfa000",
		"due_week":             "#35a77c",
		"due_far":              "#a6b0a0",
		"due_overdue_selected": "bold #f85552",
		"due_soon_selected":    "bold #dfa000",
		"due_week_selected":    "bold #35a77c",
		"due_far_selected":     "#a6b0a0",
		"state_next":           "#35a77c",
		"state_waiting":        "#dfa000",
		"state_done":           "#a6b0a0",
		"outline_thread":       "#a6b0a0",
	},
	"everforest-light-med": {
		"tab_active":           "bold #000000 on-#eaedc8",
		"tab_inactive":         "#909b92",
		"tab_agenda":           "#35a77c",
		"tab_next":             "#8da101",
		"tab_quadrants":        "#dfa000",
		"tab_inbox":            "#d699b6",
		"tab_projects":         "#3a94c5",
		"tab_agenda_active":    "bold #35a77c on-#eaedc8",
		"tab_next_active":      "bold #8da101 on-#eaedc8",
		"tab_quadrants_active": "bold #dfa000 on-#eaedc8",
		"tab_inbox_active":     "bold #d699b6 on-#eaedc8",
		"tab_projects_active":  "bold #3a94c5 on-#eaedc8",
		"selection":            "#000000 on-#eaedc8",
		"accent":               "#35a77c",
		"prompt":               "bold #35a77c",
		"section":              "bold #5c6a72",
		"approval_section":     "bold #dfa000",
		"inbox_section":        "bold #d699b6",
		"modal_title":          "bold #000000 on-#eaedc8",
		"border":               "#a6b0a0",
		"border_gradient":      "#3a94c5 #d699b6 @45",
		"form_group_label":     "bold #000000 on-#35a77c",
		"context":              "bold #83c092",
		"context_selected":     "bold #83c092",
		"project":              "#d699b6",
		"project_selected":     "bold #d699b6",
		"title_selected":       "bold",
		"priority":             "bold #dfa000",
		"priority_selected":    "bold #dfa000",
		"muted":                "#909b92",
		"muted_selected":       "#909b92",
		"note":                 "#85908b",
		"description":          "#85908b",
		"link":                 "underline #3a94c5",
		"detail_label":         "bold #8c9890",
		"link_system":          "#35a77c",
		"error":                "#f85552",
		"warning":              "#dfa000",
		"due_overdue":          "#f85552",
		"due_soon":             "#dfa000",
		"due_week":             "#35a77c",
		"due_far":              "#a6b0a0",
		"due_overdue_selected": "bold #f85552",
		"due_soon_selected":    "bold #dfa000",
		"due_week_selected":    "bold #35a77c",
		"due_far_selected":     "#a6b0a0",
		"state_next":           "#35a77c",
		"state_waiting":        "#dfa000",
		"state_done":           "#a6b0a0",
		"outline_thread":       "#a6b0a0",
	},
	"gruvbox-dark": {
		"tab_active":           "bold #ffffff on-#665c54",
		"tab_inactive":         "#ad9d87",
		"tab_agenda":           "#8ec07c",
		"tab_next":             "#b8bb26",
		"tab_quadrants":        "#fabd2f",
		"tab_inbox":            "#b16286",
		"tab_projects":         "#83a598",
		"tab_agenda_active":    "bold #8ec07c on-#665c54",
		"tab_next_active":      "bold #b8bb26 on-#665c54",
		"tab_quadrants_active": "bold #fabd2f on-#665c54",
		"tab_inbox_active":     "bold #b16286 on-#665c54",
		"tab_projects_active":  "bold #83a598 on-#665c54",
		"selection":            "#ffffff on-#665c54",
		"accent":               "#8ec07c",
		"prompt":               "bold #8ec07c",
		"section":              "bold #ebdbb2",
		"approval_section":     "bold #fabd2f",
		"inbox_section":        "bold #b16286",
		"modal_title":          "bold #ffffff on-#665c54",
		"border":               "#928374",
		"border_gradient":      "#83a598 #b16286 @45",
		"form_group_label":     "bold #000000 on-#8ec07c",
		"context":              "bold #689d6a",
		"context_selected":     "bold #689d6a",
		"project":              "#b16286",
		"project_selected":     "bold #b16286",
		"title_selected":       "bold",
		"priority":             "bold #fabd2f",
		"priority_selected":    "bold #fabd2f",
		"muted":                "#ad9d87",
		"muted_selected":       "#ad9d87",
		"note":                 "#baab90",
		"description":          "#baab90",
		"link":                 "underline #83a598",
		"detail_label":         "bold #b1a28a",
		"link_system":          "#8ec07c",
		"error":                "#fb4934",
		"warning":              "#fabd2f",
		"due_overdue":          "#fb4934",
		"due_soon":             "#fabd2f",
		"due_week":             "#8ec07c",
		"due_far":              "#928374",
		"due_overdue_selected": "bold #fb4934",
		"due_soon_selected":    "bold #fabd2f",
		"due_week_selected":    "bold #8ec07c",
		"due_far_selected":     "#928374",
		"state_next":           "#8ec07c",
		"state_waiting":        "#fabd2f",
		"state_done":           "#928374",
		"outline_thread":       "#928374",
	},
	"gruvbox-dark-hard": {
		"tab_active":           "bold #ffffff on-#665c54",
		"tab_inactive":         "#ad9d87",
		"tab_agenda":           "#8ec07c",
		"tab_next":             "#b8bb26",
		"tab_quadrants":        "#fabd2f",
		"tab_inbox":            "#b16286",
		"tab_projects":         "#83a598",
		"tab_agenda_active":    "bold #8ec07c on-#665c54",
		"tab_next_active":      "bold #b8bb26 on-#665c54",
		"tab_quadrants_active": "bold #fabd2f on-#665c54",
		"tab_inbox_active":     "bold #b16286 on-#665c54",
		"tab_projects_active":  "bold #83a598 on-#665c54",
		"selection":            "#ffffff on-#665c54",
		"accent":               "#8ec07c",
		"prompt":               "bold #8ec07c",
		"section":              "bold #ebdbb2",
		"approval_section":     "bold #fabd2f",
		"inbox_section":        "bold #b16286",
		"modal_title":          "bold #ffffff on-#665c54",
		"border":               "#928374",
		"border_gradient":      "#83a598 #b16286 @45",
		"form_group_label":     "bold #000000 on-#8ec07c",
		"context":              "bold #689d6a",
		"context_selected":     "bold #689d6a",
		"project":              "#b16286",
		"project_selected":     "bold #b16286",
		"title_selected":       "bold",
		"priority":             "bold #fabd2f",
		"priority_selected":    "bold #fabd2f",
		"muted":                "#ad9d87",
		"muted_selected":       "#ad9d87",
		"note":                 "#baab90",
		"description":          "#baab90",
		"link":                 "underline #83a598",
		"detail_label":         "bold #b1a28a",
		"link_system":          "#8ec07c",
		"error":                "#fb4934",
		"warning":              "#fabd2f",
		"due_overdue":          "#fb4934",
		"due_soon":             "#fabd2f",
		"due_week":             "#8ec07c",
		"due_far":              "#928374",
		"due_overdue_selected": "bold #fb4934",
		"due_soon_selected":    "bold #fabd2f",
		"due_week_selected":    "bold #8ec07c",
		"due_far_selected":     "#928374",
		"state_next":           "#8ec07c",
		"state_waiting":        "#fabd2f",
		"state_done":           "#928374",
		"outline_thread":       "#928374",
	},
	"gruvbox-light": {
		"tab_active":           "bold #ffffff on-#3c3836",
		"tab_inactive":         "#786c61",
		"tab_agenda":           "#427b58",
		"tab_next":             "#79740e",
		"tab_quadrants":        "#b57614",
		"tab_inbox":            "#b16286",
		"tab_projects":         "#076678",
		"tab_agenda_active":    "bold #427b58 on-#3c3836",
		"tab_next_active":      "bold #79740e on-#3c3836",
		"tab_quadrants_active": "bold #b57614 on-#3c3836",
		"tab_inbox_active":     "bold #b16286 on-#3c3836",
		"tab_projects_active":  "bold #076678 on-#3c3836",
		"selection":            "#ffffff on-#3c3836",
		"accent":               "#427b58",
		"prompt":               "bold #427b58",
		"section":              "bold #3c3836",
		"approval_section":     "bold #b57614",
		"inbox_section":        "bold #b16286",
		"modal_title":          "bold #ffffff on-#3c3836",
		"border":               "#928374",
		"border_gradient":      "#076678 #b16286 @45",
		"form_group_label":     "bold #ffffff on-#427b58",
		"context":              "bold #689d6a",
		"context_selected":     "bold #689d6a",
		"project":              "#b16286",
		"project_selected":     "bold #b16286",
		"title_selected":       "bold",
		"priority":             "bold #b57614",
		"priority_selected":    "bold #b57614",
		"muted":                "#786c61",
		"muted_selected":       "#786c61",
		"note":                 "#6b6158",
		"description":          "#6b6158",
		"link":                 "underline #076678",
		"detail_label":         "bold #74695e",
		"link_system":          "#427b58",
		"error":                "#9d0006",
		"warning":              "#b57614",
		"due_overdue":          "#9d0006",
		"due_soon":             "#b57614",
		"due_week":             "#427b58",
		"due_far":              "#928374",
		"due_overdue_selected": "bold #9d0006",
		"due_soon_selected":    "bold #b57614",
		"due_week_selected":    "bold #427b58",
		"due_far_selected":     "#928374",
		"state_next":           "#427b58",
		"state_waiting":        "#b57614",
		"state_done":           "#928374",
		"outline_thread":       "#928374",
	},
	"gruvbox-material-dark": {
		"tab_active":           "bold #000000 on-#d4be98",
		"tab_inactive":         "#968774",
		"tab_agenda":           "#89b482",
		"tab_next":             "#a9b665",
		"tab_quadrants":        "#d8a657",
		"tab_inbox":            "#d3869b",
		"tab_projects":         "#7daea3",
		"tab_agenda_active":    "bold #89b482 on-#d4be98",
		"tab_next_active":      "bold #a9b665 on-#d4be98",
		"tab_quadrants_active": "bold #d8a657 on-#d4be98",
		"tab_inbox_active":     "bold #d3869b on-#d4be98",
		"tab_projects_active":  "bold #7daea3 on-#d4be98",
		"selection":            "#000000 on-#d4be98",
		"accent":               "#89b482",
		"prompt":               "bold #89b482",
		"section":              "bold #d4be98",
		"approval_section":     "bold #d8a657",
		"inbox_section":        "bold #d3869b",
		"modal_title":          "bold #000000 on-#d4be98",
		"border":               "#7c6f64",
		"border_gradient":      "#7daea3 #d3869b @45",
		"form_group_label":     "bold #000000 on-#89b482",
		"context":              "bold #89b482",
		"context_selected":     "bold #89b482",
		"project":              "#d3869b",
		"project_selected":     "bold #d3869b",
		"title_selected":       "bold",
		"priority":             "bold #d8a657",
		"priority_selected":    "bold #d8a657",
		"muted":                "#968774",
		"muted_selected":       "#968774",
		"note":                 "#a4937b",
		"description":          "#a4937b",
		"link":                 "underline #7daea3",
		"detail_label":         "bold #9b8b76",
		"link_system":          "#89b482",
		"error":                "#ea6962",
		"warning":              "#d8a657",
		"due_overdue":          "#ea6962",
		"due_soon":             "#d8a657",
		"due_week":             "#89b482",
		"due_far":              "#7c6f64",
		"due_overdue_selected": "bold #ea6962",
		"due_soon_selected":    "bold #d8a657",
		"due_week_selected":    "bold #89b482",
		"due_far_selected":     "#7c6f64",
		"state_next":           "#89b482",
		"state_waiting":        "#d8a657",
		"state_done":           "#7c6f64",
		"outline_thread":       "#7c6f64",
	},
	"gruvbox-material-light": {
		"tab_active":           "bold #ffffff on-#654735",
		"tab_inactive":         "#94806c",
		"tab_agenda":           "#4c7a5d",
		"tab_next":             "#6c782e",
		"tab_quadrants":        "#b47109",
		"tab_inbox":            "#945e80",
		"tab_projects":         "#45707a",
		"tab_agenda_active":    "bold #4c7a5d on-#654735",
		"tab_next_active":      "bold #6c782e on-#654735",
		"tab_quadrants_active": "bold #b47109 on-#654735",
		"tab_inbox_active":     "bold #945e80 on-#654735",
		"tab_projects_active":  "bold #45707a on-#654735",
		"selection":            "#ffffff on-#654735",
		"accent":               "#4c7a5d",
		"prompt":               "bold #4c7a5d",
		"section":              "bold #654735",
		"approval_section":     "bold #b47109",
		"inbox_section":        "bold #945e80",
		"modal_title":          "bold #ffffff on-#654735",
		"border":               "#a89984",
		"border_gradient":      "#45707a #945e80 @45",
		"form_group_label":     "bold #ffffff on-#4c7a5d",
		"context":              "bold #4c7a5d",
		"context_selected":     "bold #4c7a5d",
		"project":              "#945e80",
		"project_selected":     "bold #945e80",
		"title_selected":       "bold",
		"priority":             "bold #b47109",
		"priority_selected":    "bold #b47109",
		"muted":                "#94806c",
		"muted_selected":       "#94806c",
		"note":                 "#8a7460",
		"description":          "#8a7460",
		"link":                 "underline #45707a",
		"detail_label":         "bold #917c68",
		"link_system":          "#4c7a5d",
		"error":                "#c14a4a",
		"warning":              "#b47109",
		"due_overdue":          "#c14a4a",
		"due_soon":             "#b47109",
		"due_week":             "#4c7a5d",
		"due_far":              "#a89984",
		"due_overdue_selected": "bold #c14a4a",
		"due_soon_selected":    "bold #b47109",
		"due_week_selected":    "bold #4c7a5d",
		"due_far_selected":     "#a89984",
		"state_next":           "#4c7a5d",
		"state_waiting":        "#b47109",
		"state_done":           "#a89984",
		"outline_thread":       "#a89984",
	},
	"solarized-dark": {
		"tab_active":           "bold #ffffff on-#073642",
		"tab_inactive":         "#4b6e76",
		"tab_agenda":           "#93a1a1",
		"tab_next":             "#586e75",
		"tab_quadrants":        "#657b83",
		"tab_inbox":            "#d33682",
		"tab_projects":         "#839496",
		"tab_agenda_active":    "bold #93a1a1 on-#073642",
		"tab_next_active":      "bold #586e75 on-#073642",
		"tab_quadrants_active": "bold #657b83 on-#073642",
		"tab_inbox_active":     "bold #d33682 on-#073642",
		"tab_projects_active":  "bold #839496 on-#073642",
		"selection":            "#ffffff on-#073642",
		"accent":               "#93a1a1",
		"prompt":               "bold #93a1a1",
		"section":              "bold #839496",
		"approval_section":     "bold #657b83",
		"inbox_section":        "bold #d33682",
		"modal_title":          "bold #ffffff on-#073642",
		"border":               "#335e69",
		"border_gradient":      "#839496 #d33682 @45",
		"form_group_label":     "bold #000000 on-#93a1a1",
		"context":              "bold #2aa198",
		"context_selected":     "bold #2aa198",
		"project":              "#d33682",
		"project_selected":     "bold #d33682",
		"title_selected":       "bold",
		"priority":             "bold #657b83",
		"priority_selected":    "bold #657b83",
		"muted":                "#4b6e76",
		"muted_selected":       "#4b6e76",
		"note":                 "#57767d",
		"description":          "#57767d",
		"link":                 "underline #839496",
		"detail_label":         "bold #4f7179",
		"link_system":          "#93a1a1",
		"error":                "#cb4b16",
		"warning":              "#657b83",
		"due_overdue":          "#cb4b16",
		"due_soon":             "#657b83",
		"due_week":             "#93a1a1",
		"due_far":              "#335e69",
		"due_overdue_selected": "bold #cb4b16",
		"due_soon_selected":    "bold #657b83",
		"due_week_selected":    "bold #93a1a1",
		"due_far_selected":     "#335e69",
		"state_next":           "#93a1a1",
		"state_waiting":        "#657b83",
		"state_done":           "#335e69",
		"outline_thread":       "#335e69",
	},
	"solarized-light": {
		"tab_active":           "bold #000000 on-#eee8d5",
		"tab_inactive":         "#1e434d",
		"tab_agenda":           "#93a1a1",
		"tab_next":             "#586e75",
		"tab_quadrants":        "#657b83",
		"tab_inbox":            "#d33682",
		"tab_projects":         "#839496",
		"tab_agenda_active":    "bold #93a1a1 on-#eee8d5",
		"tab_next_active":      "bold #586e75 on-#eee8d5",
		"tab_quadrants_active": "bold #657b83 on-#eee8d5",
		"tab_inbox_active":     "bold #d33682 on-#eee8d5",
		"tab_projects_active":  "bold #839496 on-#eee8d5",
		"selection":            "#000000 on-#eee8d5",
		"accent":               "#93a1a1",
		"prompt":               "bold #93a1a1",
		"section":              "bold #657b83",
		"approval_section":     "bold #657b83",
		"inbox_section":        "bold #d33682",
		"modal_title":          "bold #000000 on-#eee8d5",
		"border":               "#002b36",
		"border_gradient":      "#839496 #d33682 @45",
		"form_group_label":     "bold #000000 on-#93a1a1",
		"context":              "bold #2aa198",
		"context_selected":     "bold #2aa198",
		"project":              "#d33682",
		"project_selected":     "bold #d33682",
		"title_selected":       "bold",
		"priority":             "bold #657b83",
		"priority_selected":    "bold #657b83",
		"muted":                "#1e434d",
		"muted_selected":       "#1e434d",
		"note":                 "#2d4f59",
		"description":          "#2d4f59",
		"link":                 "underline #839496",
		"detail_label":         "bold #234751",
		"link_system":          "#93a1a1",
		"error":                "#cb4b16",
		"warning":              "#657b83",
		"due_overdue":          "#cb4b16",
		"due_soon":             "#657b83",
		"due_week":             "#93a1a1",
		"due_far":              "#002b36",
		"due_overdue_selected": "bold #cb4b16",
		"due_soon_selected":    "bold #657b83",
		"due_week_selected":    "bold #93a1a1",
		"due_far_selected":     "#002b36",
		"state_next":           "#93a1a1",
		"state_waiting":        "#657b83",
		"state_done":           "#002b36",
		"outline_thread":       "#002b36",
	},
	"kanagawa-dragon": {
		"tab_active":           "bold #000000 on-#c5c9c5",
		"tab_inactive":         "#afb0a8",
		"tab_agenda":           "#7aa89f",
		"tab_next":             "#87a987",
		"tab_quadrants":        "#e6c384",
		"tab_inbox":            "#a292a3",
		"tab_projects":         "#7fb4ca",
		"tab_agenda_active":    "bold #7aa89f on-#c5c9c5",
		"tab_next_active":      "bold #87a987 on-#c5c9c5",
		"tab_quadrants_active": "bold #e6c384 on-#c5c9c5",
		"tab_inbox_active":     "bold #a292a3 on-#c5c9c5",
		"tab_projects_active":  "bold #7fb4ca on-#c5c9c5",
		"selection":            "#000000 on-#c5c9c5",
		"accent":               "#7aa89f",
		"prompt":               "bold #7aa89f",
		"section":              "bold #c5c9c5",
		"approval_section":     "bold #e6c384",
		"inbox_section":        "bold #a292a3",
		"modal_title":          "bold #000000 on-#c5c9c5",
		"border":               "#a6a69c",
		"border_gradient":      "#7fb4ca #a292a3 @45",
		"form_group_label":     "bold #000000 on-#7aa89f",
		"context":              "bold #8ea4a2",
		"context_selected":     "bold #8ea4a2",
		"project":              "#a292a3",
		"project_selected":     "bold #a292a3",
		"title_selected":       "bold",
		"priority":             "bold #e6c384",
		"priority_selected":    "bold #e6c384",
		"muted":                "#afb0a8",
		"muted_selected":       "#afb0a8",
		"note":                 "#b4b6ae",
		"description":          "#b4b6ae",
		"link":                 "underline #7fb4ca",
		"detail_label":         "bold #b1b2aa",
		"link_system":          "#7aa89f",
		"error":                "#e46876",
		"warning":              "#e6c384",
		"due_overdue":          "#e46876",
		"due_soon":             "#e6c384",
		"due_week":             "#7aa89f",
		"due_far":              "#a6a69c",
		"due_overdue_selected": "bold #e46876",
		"due_soon_selected":    "bold #e6c384",
		"due_week_selected":    "bold #7aa89f",
		"due_far_selected":     "#a6a69c",
		"state_next":           "#7aa89f",
		"state_waiting":        "#e6c384",
		"state_done":           "#a6a69c",
		"outline_thread":       "#a6a69c",
	},
	"kanagawa-wave": {
		"tab_active":           "bold #000000 on-#dcd7ba",
		"tab_inactive":         "#929081",
		"tab_agenda":           "#7aa89f",
		"tab_next":             "#98bb6c",
		"tab_quadrants":        "#e6c384",
		"tab_inbox":            "#957fb8",
		"tab_projects":         "#7fb4ca",
		"tab_agenda_active":    "bold #7aa89f on-#dcd7ba",
		"tab_next_active":      "bold #98bb6c on-#dcd7ba",
		"tab_quadrants_active": "bold #e6c384 on-#dcd7ba",
		"tab_inbox_active":     "bold #957fb8 on-#dcd7ba",
		"tab_projects_active":  "bold #7fb4ca on-#dcd7ba",
		"selection":            "#000000 on-#dcd7ba",
		"accent":               "#7aa89f",
		"prompt":               "bold #7aa89f",
		"section":              "bold #dcd7ba",
		"approval_section":     "bold #e6c384",
		"inbox_section":        "bold #957fb8",
		"modal_title":          "bold #000000 on-#dcd7ba",
		"border":               "#727169",
		"border_gradient":      "#7fb4ca #957fb8 @45",
		"form_group_label":     "bold #000000 on-#7aa89f",
		"context":              "bold #6a9589",
		"context_selected":     "bold #6a9589",
		"project":              "#957fb8",
		"project_selected":     "bold #957fb8",
		"title_selected":       "bold",
		"priority":             "bold #e6c384",
		"priority_selected":    "bold #e6c384",
		"muted":                "#929081",
		"muted_selected":       "#929081",
		"note":                 "#a29f8d",
		"description":          "#a29f8d",
		"link":                 "underline #7fb4ca",
		"detail_label":         "bold #979585",
		"link_system":          "#7aa89f",
		"error":                "#e82424",
		"warning":              "#e6c384",
		"due_overdue":          "#e82424",
		"due_soon":             "#e6c384",
		"due_week":             "#7aa89f",
		"due_far":              "#727169",
		"due_overdue_selected": "bold #e82424",
		"due_soon_selected":    "bold #e6c384",
		"due_week_selected":    "bold #7aa89f",
		"due_far_selected":     "#727169",
		"state_next":           "#7aa89f",
		"state_waiting":        "#e6c384",
		"state_done":           "#727169",
		"outline_thread":       "#727169",
	},
	"molokai": {
		"tab_active":           "bold #000000 on-#b5d5ff",
		"tab_inactive":         "#747474",
		"tab_agenda":           "#51ceff",
		"tab_next":             "#b1e05f",
		"tab_quadrants":        "#fff26d",
		"tab_inbox":            "#8700ff",
		"tab_projects":         "#00afff",
		"tab_agenda_active":    "bold #51ceff on-#b5d5ff",
		"tab_next_active":      "bold #b1e05f on-#b5d5ff",
		"tab_quadrants_active": "bold #fff26d on-#b5d5ff",
		"tab_inbox_active":     "bold #8700ff on-#b5d5ff",
		"tab_projects_active":  "bold #00afff on-#b5d5ff",
		"selection":            "#000000 on-#b5d5ff",
		"accent":               "#51ceff",
		"prompt":               "bold #51ceff",
		"section":              "bold #bbbbbb",
		"approval_section":     "bold #fff26d",
		"inbox_section":        "bold #8700ff",
		"modal_title":          "bold #000000 on-#b5d5ff",
		"border":               "#555555",
		"border_gradient":      "#00afff #8700ff @45",
		"form_group_label":     "bold #000000 on-#51ceff",
		"context":              "bold #43a8d0",
		"context_selected":     "bold #43a8d0",
		"project":              "#8700ff",
		"project_selected":     "bold #8700ff",
		"title_selected":       "bold",
		"priority":             "bold #fff26d",
		"priority_selected":    "bold #fff26d",
		"muted":                "#747474",
		"muted_selected":       "#747474",
		"note":                 "#838383",
		"description":          "#838383",
		"link":                 "underline #00afff",
		"detail_label":         "bold #797979",
		"link_system":          "#51ceff",
		"error":                "#f6669d",
		"warning":              "#fff26d",
		"due_overdue":          "#f6669d",
		"due_soon":             "#fff26d",
		"due_week":             "#51ceff",
		"due_far":              "#555555",
		"due_overdue_selected": "bold #f6669d",
		"due_soon_selected":    "bold #fff26d",
		"due_week_selected":    "bold #51ceff",
		"due_far_selected":     "#555555",
		"state_next":           "#51ceff",
		"state_waiting":        "#fff26d",
		"state_done":           "#555555",
		"outline_thread":       "#555555",
	},
	"monokai-classic": {
		"tab_active":           "bold #ffffff on-#57584f",
		"tab_inactive":         "#999b90",
		"tab_agenda":           "#66d9ef",
		"tab_next":             "#a6e22e",
		"tab_quadrants":        "#e6db74",
		"tab_inbox":            "#ae81ff",
		"tab_projects":         "#fd971f",
		"tab_agenda_active":    "bold #66d9ef on-#57584f",
		"tab_next_active":      "bold #a6e22e on-#57584f",
		"tab_quadrants_active": "bold #e6db74 on-#57584f",
		"tab_inbox_active":     "bold #ae81ff on-#57584f",
		"tab_projects_active":  "bold #fd971f on-#57584f",
		"selection":            "#ffffff on-#57584f",
		"accent":               "#66d9ef",
		"prompt":               "bold #66d9ef",
		"section":              "bold #fdfff1",
		"approval_section":     "bold #e6db74",
		"inbox_section":        "bold #ae81ff",
		"modal_title":          "bold #ffffff on-#57584f",
		"border":               "#6e7066",
		"border_gradient":      "#fd971f #ae81ff @45",
		"form_group_label":     "bold #000000 on-#66d9ef",
		"context":              "bold #66d9ef",
		"context_selected":     "bold #66d9ef",
		"project":              "#ae81ff",
		"project_selected":     "bold #ae81ff",
		"title_selected":       "bold",
		"priority":             "bold #e6db74",
		"priority_selected":    "bold #e6db74",
		"muted":                "#999b90",
		"muted_selected":       "#999b90",
		"note":                 "#aeb0a5",
		"description":          "#aeb0a5",
		"link":                 "underline #fd971f",
		"detail_label":         "bold #a0a297",
		"link_system":          "#66d9ef",
		"error":                "#f92672",
		"warning":              "#e6db74",
		"due_overdue":          "#f92672",
		"due_soon":             "#e6db74",
		"due_week":             "#66d9ef",
		"due_far":              "#6e7066",
		"due_overdue_selected": "bold #f92672",
		"due_soon_selected":    "bold #e6db74",
		"due_week_selected":    "bold #66d9ef",
		"due_far_selected":     "#6e7066",
		"state_next":           "#66d9ef",
		"state_waiting":        "#e6db74",
		"state_done":           "#6e7066",
		"outline_thread":       "#6e7066",
	},
	"monokai-pro": {
		"tab_active":           "bold #ffffff on-#5b595c",
		"tab_inactive":         "#9b9a9b",
		"tab_agenda":           "#78dce8",
		"tab_next":             "#a9dc76",
		"tab_quadrants":        "#ffd866",
		"tab_inbox":            "#ab9df2",
		"tab_projects":         "#fc9867",
		"tab_agenda_active":    "bold #78dce8 on-#5b595c",
		"tab_next_active":      "bold #a9dc76 on-#5b595c",
		"tab_quadrants_active": "bold #ffd866 on-#5b595c",
		"tab_inbox_active":     "bold #ab9df2 on-#5b595c",
		"tab_projects_active":  "bold #fc9867 on-#5b595c",
		"selection":            "#ffffff on-#5b595c",
		"accent":               "#78dce8",
		"prompt":               "bold #78dce8",
		"section":              "bold #fcfcfa",
		"approval_section":     "bold #ffd866",
		"inbox_section":        "bold #ab9df2",
		"modal_title":          "bold #ffffff on-#5b595c",
		"border":               "#727072",
		"border_gradient":      "#fc9867 #ab9df2 @45",
		"form_group_label":     "bold #000000 on-#78dce8",
		"context":              "bold #78dce8",
		"context_selected":     "bold #78dce8",
		"project":              "#ab9df2",
		"project_selected":     "bold #ab9df2",
		"title_selected":       "bold",
		"priority":             "bold #ffd866",
		"priority_selected":    "bold #ffd866",
		"muted":                "#9b9a9b",
		"muted_selected":       "#9b9a9b",
		"note":                 "#b0afaf",
		"description":          "#b0afaf",
		"link":                 "underline #fc9867",
		"detail_label":         "bold #a2a1a2",
		"link_system":          "#78dce8",
		"error":                "#ff6188",
		"warning":              "#ffd866",
		"due_overdue":          "#ff6188",
		"due_soon":             "#ffd866",
		"due_week":             "#78dce8",
		"due_far":              "#727072",
		"due_overdue_selected": "bold #ff6188",
		"due_soon_selected":    "bold #ffd866",
		"due_week_selected":    "bold #78dce8",
		"due_far_selected":     "#727072",
		"state_next":           "#78dce8",
		"state_waiting":        "#ffd866",
		"state_done":           "#727072",
		"outline_thread":       "#727072",
	},
	"nord": {
		"tab_active":           "bold #000000 on-#eceff4",
		"tab_inactive":         "#7f8899",
		"tab_agenda":           "#8fbcbb",
		"tab_next":             "#a3be8c",
		"tab_quadrants":        "#ebcb8b",
		"tab_inbox":            "#b48ead",
		"tab_projects":         "#81a1c1",
		"tab_agenda_active":    "bold #8fbcbb on-#eceff4",
		"tab_next_active":      "bold #a3be8c on-#eceff4",
		"tab_quadrants_active": "bold #ebcb8b on-#eceff4",
		"tab_inbox_active":     "bold #b48ead on-#eceff4",
		"tab_projects_active":  "bold #81a1c1 on-#eceff4",
		"selection":            "#000000 on-#eceff4",
		"accent":               "#8fbcbb",
		"prompt":               "bold #8fbcbb",
		"section":              "bold #d8dee9",
		"approval_section":     "bold #ebcb8b",
		"inbox_section":        "bold #b48ead",
		"modal_title":          "bold #000000 on-#eceff4",
		"border":               "#596377",
		"border_gradient":      "#81a1c1 #b48ead @45",
		"form_group_label":     "bold #000000 on-#8fbcbb",
		"context":              "bold #88c0d0",
		"context_selected":     "bold #88c0d0",
		"project":              "#b48ead",
		"project_selected":     "bold #b48ead",
		"title_selected":       "bold",
		"priority":             "bold #ebcb8b",
		"priority_selected":    "bold #ebcb8b",
		"muted":                "#7f8899",
		"muted_selected":       "#7f8899",
		"note":                 "#929aaa",
		"description":          "#929aaa",
		"link":                 "underline #81a1c1",
		"detail_label":         "bold #858e9f",
		"link_system":          "#8fbcbb",
		"error":                "#bf616a",
		"warning":              "#ebcb8b",
		"due_overdue":          "#bf616a",
		"due_soon":             "#ebcb8b",
		"due_week":             "#8fbcbb",
		"due_far":              "#596377",
		"due_overdue_selected": "bold #bf616a",
		"due_soon_selected":    "bold #ebcb8b",
		"due_week_selected":    "bold #8fbcbb",
		"due_far_selected":     "#596377",
		"state_next":           "#8fbcbb",
		"state_waiting":        "#ebcb8b",
		"state_done":           "#596377",
		"outline_thread":       "#596377",
	},
	"nord-light": {
		"tab_active":           "bold #000000 on-#d8dee9",
		"tab_inactive":         "#495265",
		"tab_agenda":           "#82afae",
		"tab_next":             "#96b17f",
		"tab_quadrants":        "#c5a565",
		"tab_inbox":            "#b48ead",
		"tab_projects":         "#81a1c1",
		"tab_agenda_active":    "bold #82afae on-#d8dee9",
		"tab_next_active":      "bold #96b17f on-#d8dee9",
		"tab_quadrants_active": "bold #c5a565 on-#d8dee9",
		"tab_inbox_active":     "bold #b48ead on-#d8dee9",
		"tab_projects_active":  "bold #81a1c1 on-#d8dee9",
		"selection":            "#000000 on-#d8dee9",
		"accent":               "#82afae",
		"prompt":               "bold #82afae",
		"section":              "bold #414858",
		"approval_section":     "bold #c5a565",
		"inbox_section":        "bold #b48ead",
		"modal_title":          "bold #000000 on-#d8dee9",
		"border":               "#4c566a",
		"border_gradient":      "#81a1c1 #b48ead @45",
		"form_group_label":     "bold #000000 on-#82afae",
		"context":              "bold #7bb3c3",
		"context_selected":     "bold #7bb3c3",
		"project":              "#b48ead",
		"project_selected":     "bold #b48ead",
		"title_selected":       "bold",
		"priority":             "bold #c5a565",
		"priority_selected":    "bold #c5a565",
		"muted":                "#495265",
		"muted_selected":       "#495265",
		"note":                 "#475062",
		"description":          "#475062",
		"link":                 "underline #81a1c1",
		"detail_label":         "bold #485164",
		"link_system":          "#82afae",
		"error":                "#bf616a",
		"warning":              "#c5a565",
		"due_overdue":          "#bf616a",
		"due_soon":             "#c5a565",
		"due_week":             "#82afae",
		"due_far":              "#4c566a",
		"due_overdue_selected": "bold #bf616a",
		"due_soon_selected":    "bold #c5a565",
		"due_week_selected":    "bold #82afae",
		"due_far_selected":     "#4c566a",
		"state_next":           "#82afae",
		"state_waiting":        "#c5a565",
		"state_done":           "#4c566a",
		"outline_thread":       "#4c566a",
	},
	"one-half-dark": {
		"tab_active":           "bold #ffffff on-#474e5d",
		"tab_inactive":         "#838b9a",
		"tab_agenda":           "#56b6c2",
		"tab_next":             "#98c379",
		"tab_quadrants":        "#e5c07b",
		"tab_inbox":            "#c678dd",
		"tab_projects":         "#61afef",
		"tab_agenda_active":    "bold #56b6c2 on-#474e5d",
		"tab_next_active":      "bold #98c379 on-#474e5d",
		"tab_quadrants_active": "bold #e5c07b on-#474e5d",
		"tab_inbox_active":     "bold #c678dd on-#474e5d",
		"tab_projects_active":  "bold #61afef on-#474e5d",
		"selection":            "#ffffff on-#474e5d",
		"accent":               "#56b6c2",
		"prompt":               "bold #56b6c2",
		"section":              "bold #dcdfe4",
		"approval_section":     "bold #e5c07b",
		"inbox_section":        "bold #c678dd",
		"modal_title":          "bold #ffffff on-#474e5d",
		"border":               "#5d677a",
		"border_gradient":      "#61afef #c678dd @45",
		"form_group_label":     "bold #000000 on-#56b6c2",
		"context":              "bold #56b6c2",
		"context_selected":     "bold #56b6c2",
		"project":              "#c678dd",
		"project_selected":     "bold #c678dd",
		"title_selected":       "bold",
		"priority":             "bold #e5c07b",
		"priority_selected":    "bold #e5c07b",
		"muted":                "#838b9a",
		"muted_selected":       "#838b9a",
		"note":                 "#969daa",
		"description":          "#969daa",
		"link":                 "underline #61afef",
		"detail_label":         "bold #89919f",
		"link_system":          "#56b6c2",
		"error":                "#e06c75",
		"warning":              "#e5c07b",
		"due_overdue":          "#e06c75",
		"due_soon":             "#e5c07b",
		"due_week":             "#56b6c2",
		"due_far":              "#5d677a",
		"due_overdue_selected": "bold #e06c75",
		"due_soon_selected":    "bold #e5c07b",
		"due_week_selected":    "bold #56b6c2",
		"due_far_selected":     "#5d677a",
		"state_next":           "#56b6c2",
		"state_waiting":        "#e5c07b",
		"state_done":           "#5d677a",
		"outline_thread":       "#5d677a",
	},
	"one-half-light": {
		"tab_active":           "bold #000000 on-#bfceff",
		"tab_inactive":         "#484b56",
		"tab_agenda":           "#56b6c2",
		"tab_next":             "#98c379",
		"tab_quadrants":        "#d8b36e",
		"tab_inbox":            "#a626a4",
		"tab_projects":         "#61afef",
		"tab_agenda_active":    "bold #56b6c2 on-#bfceff",
		"tab_next_active":      "bold #98c379 on-#bfceff",
		"tab_quadrants_active": "bold #d8b36e on-#bfceff",
		"tab_inbox_active":     "bold #a626a4 on-#bfceff",
		"tab_projects_active":  "bold #61afef on-#bfceff",
		"selection":            "#000000 on-#bfceff",
		"accent":               "#56b6c2",
		"prompt":               "bold #56b6c2",
		"section":              "bold #383a42",
		"approval_section":     "bold #d8b36e",
		"inbox_section":        "bold #a626a4",
		"modal_title":          "bold #000000 on-#bfceff",
		"border":               "#4f525e",
		"border_gradient":      "#61afef #a626a4 @45",
		"form_group_label":     "bold #000000 on-#56b6c2",
		"context":              "bold #0997b3",
		"context_selected":     "bold #0997b3",
		"project":              "#a626a4",
		"project_selected":     "bold #a626a4",
		"title_selected":       "bold",
		"priority":             "bold #d8b36e",
		"priority_selected":    "bold #d8b36e",
		"muted":                "#484b56",
		"muted_selected":       "#484b56",
		"note":                 "#454751",
		"description":          "#454751",
		"link":                 "underline #61afef",
		"detail_label":         "bold #474a54",
		"link_system":          "#56b6c2",
		"error":                "#e06c75",
		"warning":              "#d8b36e",
		"due_overdue":          "#e06c75",
		"due_soon":             "#d8b36e",
		"due_week":             "#56b6c2",
		"due_far":              "#4f525e",
		"due_overdue_selected": "bold #e06c75",
		"due_soon_selected":    "bold #d8b36e",
		"due_week_selected":    "bold #56b6c2",
		"due_far_selected":     "#4f525e",
		"state_next":           "#56b6c2",
		"state_waiting":        "#d8b36e",
		"state_done":           "#4f525e",
		"outline_thread":       "#4f525e",
	},
	"rose-pine": {
		"tab_active":           "bold #ffffff on-#403d52",
		"tab_inactive":         "#908da7",
		"tab_agenda":           "#ebbcba",
		"tab_next":             "#31748f",
		"tab_quadrants":        "#f6c177",
		"tab_inbox":            "#c4a7e7",
		"tab_projects":         "#9ccfd8",
		"tab_agenda_active":    "bold #ebbcba on-#403d52",
		"tab_next_active":      "bold #31748f on-#403d52",
		"tab_quadrants_active": "bold #f6c177 on-#403d52",
		"tab_inbox_active":     "bold #c4a7e7 on-#403d52",
		"tab_projects_active":  "bold #9ccfd8 on-#403d52",
		"selection":            "#ffffff on-#403d52",
		"accent":               "#ebbcba",
		"prompt":               "bold #ebbcba",
		"section":              "bold #e0def4",
		"approval_section":     "bold #f6c177",
		"inbox_section":        "bold #c4a7e7",
		"modal_title":          "bold #ffffff on-#403d52",
		"border":               "#6e6a86",
		"border_gradient":      "#9ccfd8 #c4a7e7 @45",
		"form_group_label":     "bold #000000 on-#ebbcba",
		"context":              "bold #ebbcba",
		"context_selected":     "bold #ebbcba",
		"project":              "#c4a7e7",
		"project_selected":     "bold #c4a7e7",
		"title_selected":       "bold",
		"priority":             "bold #f6c177",
		"priority_selected":    "bold #f6c177",
		"muted":                "#908da7",
		"muted_selected":       "#908da7",
		"note":                 "#a19eb8",
		"description":          "#a19eb8",
		"link":                 "underline #9ccfd8",
		"detail_label":         "bold #9693ac",
		"link_system":          "#ebbcba",
		"error":                "#eb6f92",
		"warning":              "#f6c177",
		"due_overdue":          "#eb6f92",
		"due_soon":             "#f6c177",
		"due_week":             "#ebbcba",
		"due_far":              "#6e6a86",
		"due_overdue_selected": "bold #eb6f92",
		"due_soon_selected":    "bold #f6c177",
		"due_week_selected":    "bold #ebbcba",
		"due_far_selected":     "#6e6a86",
		"state_next":           "#ebbcba",
		"state_waiting":        "#f6c177",
		"state_done":           "#6e6a86",
		"outline_thread":       "#6e6a86",
	},
	"rose-pine-dawn": {
		"tab_active":           "bold #000000 on-#dfdad9",
		"tab_inactive":         "#848098",
		"tab_agenda":           "#d7827e",
		"tab_next":             "#286983",
		"tab_quadrants":        "#ea9d34",
		"tab_inbox":            "#907aa9",
		"tab_projects":         "#56949f",
		"tab_agenda_active":    "bold #d7827e on-#dfdad9",
		"tab_next_active":      "bold #286983 on-#dfdad9",
		"tab_quadrants_active": "bold #ea9d34 on-#dfdad9",
		"tab_inbox_active":     "bold #907aa9 on-#dfdad9",
		"tab_projects_active":  "bold #56949f on-#dfdad9",
		"selection":            "#000000 on-#dfdad9",
		"accent":               "#d7827e",
		"prompt":               "bold #d7827e",
		"section":              "bold #575279",
		"approval_section":     "bold #ea9d34",
		"inbox_section":        "bold #907aa9",
		"modal_title":          "bold #000000 on-#dfdad9",
		"border":               "#9893a5",
		"border_gradient":      "#56949f #907aa9 @45",
		"form_group_label":     "bold #000000 on-#d7827e",
		"context":              "bold #d7827e",
		"context_selected":     "bold #d7827e",
		"project":              "#907aa9",
		"project_selected":     "bold #907aa9",
		"title_selected":       "bold",
		"priority":             "bold #ea9d34",
		"priority_selected":    "bold #ea9d34",
		"muted":                "#848098",
		"muted_selected":       "#848098",
		"note":                 "#7b7691",
		"description":          "#7b7691",
		"link":                 "underline #56949f",
		"detail_label":         "bold #817c96",
		"link_system":          "#d7827e",
		"error":                "#b4637a",
		"warning":              "#ea9d34",
		"due_overdue":          "#b4637a",
		"due_soon":             "#ea9d34",
		"due_week":             "#d7827e",
		"due_far":              "#9893a5",
		"due_overdue_selected": "bold #b4637a",
		"due_soon_selected":    "bold #ea9d34",
		"due_week_selected":    "bold #d7827e",
		"due_far_selected":     "#9893a5",
		"state_next":           "#d7827e",
		"state_waiting":        "#ea9d34",
		"state_done":           "#9893a5",
		"outline_thread":       "#9893a5",
	},
	"rose-pine-moon": {
		"tab_active":           "bold #ffffff on-#44415a",
		"tab_inactive":         "#908da7",
		"tab_agenda":           "#ea9a97",
		"tab_next":             "#3e8fb0",
		"tab_quadrants":        "#f6c177",
		"tab_inbox":            "#c4a7e7",
		"tab_projects":         "#9ccfd8",
		"tab_agenda_active":    "bold #ea9a97 on-#44415a",
		"tab_next_active":      "bold #3e8fb0 on-#44415a",
		"tab_quadrants_active": "bold #f6c177 on-#44415a",
		"tab_inbox_active":     "bold #c4a7e7 on-#44415a",
		"tab_projects_active":  "bold #9ccfd8 on-#44415a",
		"selection":            "#ffffff on-#44415a",
		"accent":               "#ea9a97",
		"prompt":               "bold #ea9a97",
		"section":              "bold #e0def4",
		"approval_section":     "bold #f6c177",
		"inbox_section":        "bold #c4a7e7",
		"modal_title":          "bold #ffffff on-#44415a",
		"border":               "#6e6a86",
		"border_gradient":      "#9ccfd8 #c4a7e7 @45",
		"form_group_label":     "bold #000000 on-#ea9a97",
		"context":              "bold #ea9a97",
		"context_selected":     "bold #ea9a97",
		"project":              "#c4a7e7",
		"project_selected":     "bold #c4a7e7",
		"title_selected":       "bold",
		"priority":             "bold #f6c177",
		"priority_selected":    "bold #f6c177",
		"muted":                "#908da7",
		"muted_selected":       "#908da7",
		"note":                 "#a19eb8",
		"description":          "#a19eb8",
		"link":                 "underline #9ccfd8",
		"detail_label":         "bold #9693ac",
		"link_system":          "#ea9a97",
		"error":                "#eb6f92",
		"warning":              "#f6c177",
		"due_overdue":          "#eb6f92",
		"due_soon":             "#f6c177",
		"due_week":             "#ea9a97",
		"due_far":              "#6e6a86",
		"due_overdue_selected": "bold #eb6f92",
		"due_soon_selected":    "bold #f6c177",
		"due_week_selected":    "bold #ea9a97",
		"due_far_selected":     "#6e6a86",
		"state_next":           "#ea9a97",
		"state_waiting":        "#f6c177",
		"state_done":           "#6e6a86",
		"outline_thread":       "#6e6a86",
	},
	"tokyonight": {
		"tab_active":           "bold #ffffff on-#33467c",
		"tab_inactive":         "#676f92",
		"tab_agenda":           "#7dcfff",
		"tab_next":             "#9ece6a",
		"tab_quadrants":        "#e0af68",
		"tab_inbox":            "#bb9af7",
		"tab_projects":         "#7aa2f7",
		"tab_agenda_active":    "bold #7dcfff on-#33467c",
		"tab_next_active":      "bold #9ece6a on-#33467c",
		"tab_quadrants_active": "bold #e0af68 on-#33467c",
		"tab_inbox_active":     "bold #bb9af7 on-#33467c",
		"tab_projects_active":  "bold #7aa2f7 on-#33467c",
		"selection":            "#ffffff on-#33467c",
		"accent":               "#7dcfff",
		"prompt":               "bold #7dcfff",
		"section":              "bold #c0caf5",
		"approval_section":     "bold #e0af68",
		"inbox_section":        "bold #bb9af7",
		"modal_title":          "bold #ffffff on-#33467c",
		"border":               "#414868",
		"border_gradient":      "#7aa2f7 #bb9af7 @45",
		"form_group_label":     "bold #000000 on-#7dcfff",
		"context":              "bold #7dcfff",
		"context_selected":     "bold #7dcfff",
		"project":              "#bb9af7",
		"project_selected":     "bold #bb9af7",
		"title_selected":       "bold",
		"priority":             "bold #e0af68",
		"priority_selected":    "bold #e0af68",
		"muted":                "#676f92",
		"muted_selected":       "#676f92",
		"note":                 "#7a82a7",
		"description":          "#7a82a7",
		"link":                 "underline #7aa2f7",
		"detail_label":         "bold #6d7699",
		"link_system":          "#7dcfff",
		"error":                "#f7768e",
		"warning":              "#e0af68",
		"due_overdue":          "#f7768e",
		"due_soon":             "#e0af68",
		"due_week":             "#7dcfff",
		"due_far":              "#414868",
		"due_overdue_selected": "bold #f7768e",
		"due_soon_selected":    "bold #e0af68",
		"due_week_selected":    "bold #7dcfff",
		"due_far_selected":     "#414868",
		"state_next":           "#7dcfff",
		"state_waiting":        "#e0af68",
		"state_done":           "#414868",
		"outline_thread":       "#414868",
	},
	"tokyonight-day": {
		"tab_active":           "bold #000000 on-#99a7df",
		"tab_inactive":         "#8191c3",
		"tab_agenda":           "#007197",
		"tab_next":             "#587539",
		"tab_quadrants":        "#8c6c3e",
		"tab_inbox":            "#9854f1",
		"tab_projects":         "#2e7de9",
		"tab_agenda_active":    "bold #007197 on-#99a7df",
		"tab_next_active":      "bold #587539 on-#99a7df",
		"tab_quadrants_active": "bold #8c6c3e on-#99a7df",
		"tab_inbox_active":     "bold #9854f1 on-#99a7df",
		"tab_projects_active":  "bold #2e7de9 on-#99a7df",
		"selection":            "#000000 on-#99a7df",
		"accent":               "#007197",
		"prompt":               "bold #007197",
		"section":              "bold #3760bf",
		"approval_section":     "bold #8c6c3e",
		"inbox_section":        "bold #9854f1",
		"modal_title":          "bold #000000 on-#99a7df",
		"border":               "#a1a6c5",
		"border_gradient":      "#2e7de9 #9854f1 @45",
		"form_group_label":     "bold #ffffff on-#007197",
		"context":              "bold #007197",
		"context_selected":     "bold #007197",
		"project":              "#9854f1",
		"project_selected":     "bold #9854f1",
		"title_selected":       "bold",
		"priority":             "bold #8c6c3e",
		"priority_selected":    "bold #8c6c3e",
		"muted":                "#8191c3",
		"muted_selected":       "#8191c3",
		"note":                 "#7186c2",
		"description":          "#7186c2",
		"link":                 "underline #2e7de9",
		"detail_label":         "bold #7c8ec3",
		"link_system":          "#007197",
		"error":                "#f52a65",
		"warning":              "#8c6c3e",
		"due_overdue":          "#f52a65",
		"due_soon":             "#8c6c3e",
		"due_week":             "#007197",
		"due_far":              "#a1a6c5",
		"due_overdue_selected": "bold #f52a65",
		"due_soon_selected":    "bold #8c6c3e",
		"due_week_selected":    "bold #007197",
		"due_far_selected":     "#a1a6c5",
		"state_next":           "#007197",
		"state_waiting":        "#8c6c3e",
		"state_done":           "#a1a6c5",
		"outline_thread":       "#a1a6c5",
	},
	"tokyonight-moon": {
		"tab_active":           "bold #ffffff on-#2d3f76",
		"tab_inactive":         "#6c739a",
		"tab_agenda":           "#86e1fc",
		"tab_next":             "#c3e88d",
		"tab_quadrants":        "#ffc777",
		"tab_inbox":            "#c099ff",
		"tab_projects":         "#82aaff",
		"tab_agenda_active":    "bold #86e1fc on-#2d3f76",
		"tab_next_active":      "bold #c3e88d on-#2d3f76",
		"tab_quadrants_active": "bold #ffc777 on-#2d3f76",
		"tab_inbox_active":     "bold #c099ff on-#2d3f76",
		"tab_projects_active":  "bold #82aaff on-#2d3f76",
		"selection":            "#ffffff on-#2d3f76",
		"accent":               "#86e1fc",
		"prompt":               "bold #86e1fc",
		"section":              "bold #c8d3f5",
		"approval_section":     "bold #ffc777",
		"inbox_section":        "bold #c099ff",
		"modal_title":          "bold #ffffff on-#2d3f76",
		"border":               "#444a73",
		"border_gradient":      "#82aaff #c099ff @45",
		"form_group_label":     "bold #000000 on-#86e1fc",
		"context":              "bold #86e1fc",
		"context_selected":     "bold #86e1fc",
		"project":              "#c099ff",
		"project_selected":     "bold #c099ff",
		"title_selected":       "bold",
		"priority":             "bold #ffc777",
		"priority_selected":    "bold #ffc777",
		"muted":                "#6c739a",
		"muted_selected":       "#6c739a",
		"note":                 "#7f88ae",
		"description":          "#7f88ae",
		"link":                 "underline #82aaff",
		"detail_label":         "bold #727aa0",
		"link_system":          "#86e1fc",
		"error":                "#ff757f",
		"warning":              "#ffc777",
		"due_overdue":          "#ff757f",
		"due_soon":             "#ffc777",
		"due_week":             "#86e1fc",
		"due_far":              "#444a73",
		"due_overdue_selected": "bold #ff757f",
		"due_soon_selected":    "bold #ffc777",
		"due_week_selected":    "bold #86e1fc",
		"due_far_selected":     "#444a73",
		"state_next":           "#86e1fc",
		"state_waiting":        "#ffc777",
		"state_done":           "#444a73",
		"outline_thread":       "#444a73",
	},
	"tokyonight-night": {
		"tab_active":           "bold #ffffff on-#283457",
		"tab_inactive":         "#676f92",
		"tab_agenda":           "#7dcfff",
		"tab_next":             "#9ece6a",
		"tab_quadrants":        "#e0af68",
		"tab_inbox":            "#bb9af7",
		"tab_projects":         "#7aa2f7",
		"tab_agenda_active":    "bold #7dcfff on-#283457",
		"tab_next_active":      "bold #9ece6a on-#283457",
		"tab_quadrants_active": "bold #e0af68 on-#283457",
		"tab_inbox_active":     "bold #bb9af7 on-#283457",
		"tab_projects_active":  "bold #7aa2f7 on-#283457",
		"selection":            "#ffffff on-#283457",
		"accent":               "#7dcfff",
		"prompt":               "bold #7dcfff",
		"section":              "bold #c0caf5",
		"approval_section":     "bold #e0af68",
		"inbox_section":        "bold #bb9af7",
		"modal_title":          "bold #ffffff on-#283457",
		"border":               "#414868",
		"border_gradient":      "#7aa2f7 #bb9af7 @45",
		"form_group_label":     "bold #000000 on-#7dcfff",
		"context":              "bold #7dcfff",
		"context_selected":     "bold #7dcfff",
		"project":              "#bb9af7",
		"project_selected":     "bold #bb9af7",
		"title_selected":       "bold",
		"priority":             "bold #e0af68",
		"priority_selected":    "bold #e0af68",
		"muted":                "#676f92",
		"muted_selected":       "#676f92",
		"note":                 "#7a82a7",
		"description":          "#7a82a7",
		"link":                 "underline #7aa2f7",
		"detail_label":         "bold #6d7699",
		"link_system":          "#7dcfff",
		"error":                "#f7768e",
		"warning":              "#e0af68",
		"due_overdue":          "#f7768e",
		"due_soon":             "#e0af68",
		"due_week":             "#7dcfff",
		"due_far":              "#414868",
		"due_overdue_selected": "bold #f7768e",
		"due_soon_selected":    "bold #e0af68",
		"due_week_selected":    "bold #7dcfff",
		"due_far_selected":     "#414868",
		"state_next":           "#7dcfff",
		"state_waiting":        "#e0af68",
		"state_done":           "#414868",
		"outline_thread":       "#414868",
	},
	"tokyonight-storm": {
		"tab_active":           "bold #ffffff on-#364a82",
		"tab_inactive":         "#70789b",
		"tab_agenda":           "#7dcfff",
		"tab_next":             "#9ece6a",
		"tab_quadrants":        "#e0af68",
		"tab_inbox":            "#bb9af7",
		"tab_projects":         "#7aa2f7",
		"tab_agenda_active":    "bold #7dcfff on-#364a82",
		"tab_next_active":      "bold #9ece6a on-#364a82",
		"tab_quadrants_active": "bold #e0af68 on-#364a82",
		"tab_inbox_active":     "bold #bb9af7 on-#364a82",
		"tab_projects_active":  "bold #7aa2f7 on-#364a82",
		"selection":            "#ffffff on-#364a82",
		"accent":               "#7dcfff",
		"prompt":               "bold #7dcfff",
		"section":              "bold #c0caf5",
		"approval_section":     "bold #e0af68",
		"inbox_section":        "bold #bb9af7",
		"modal_title":          "bold #ffffff on-#364a82",
		"border":               "#4e5575",
		"border_gradient":      "#7aa2f7 #bb9af7 @45",
		"form_group_label":     "bold #000000 on-#7dcfff",
		"context":              "bold #7dcfff",
		"context_selected":     "bold #7dcfff",
		"project":              "#bb9af7",
		"project_selected":     "bold #bb9af7",
		"title_selected":       "bold",
		"priority":             "bold #e0af68",
		"priority_selected":    "bold #e0af68",
		"muted":                "#70789b",
		"muted_selected":       "#70789b",
		"note":                 "#818aaf",
		"description":          "#818aaf",
		"link":                 "underline #7aa2f7",
		"detail_label":         "bold #767ea2",
		"link_system":          "#7dcfff",
		"error":                "#f7768e",
		"warning":              "#e0af68",
		"due_overdue":          "#f7768e",
		"due_soon":             "#e0af68",
		"due_week":             "#7dcfff",
		"due_far":              "#4e5575",
		"due_overdue_selected": "bold #f7768e",
		"due_soon_selected":    "bold #e0af68",
		"due_week_selected":    "bold #7dcfff",
		"due_far_selected":     "#4e5575",
		"state_next":           "#7dcfff",
		"state_waiting":        "#e0af68",
		"state_done":           "#4e5575",
		"outline_thread":       "#4e5575",
	},
	"tomorrow-night": {
		"tab_active":           "bold #ffffff on-#373b41",
		"tab_inactive":         "#707171",
		"tab_agenda":           "#8abeb7",
		"tab_next":             "#b5bd68",
		"tab_quadrants":        "#f0c674",
		"tab_inbox":            "#b294bb",
		"tab_projects":         "#81a2be",
		"tab_agenda_active":    "bold #8abeb7 on-#373b41",
		"tab_next_active":      "bold #b5bd68 on-#373b41",
		"tab_quadrants_active": "bold #f0c674 on-#373b41",
		"tab_inbox_active":     "bold #b294bb on-#373b41",
		"tab_projects_active":  "bold #81a2be on-#373b41",
		"selection":            "#ffffff on-#373b41",
		"accent":               "#8abeb7",
		"prompt":               "bold #8abeb7",
		"section":              "bold #c5c8c6",
		"approval_section":     "bold #f0c674",
		"inbox_section":        "bold #b294bb",
		"modal_title":          "bold #ffffff on-#373b41",
		"border":               "#4c4c4c",
		"border_gradient":      "#81a2be #b294bb @45",
		"form_group_label":     "bold #000000 on-#8abeb7",
		"context":              "bold #8abeb7",
		"context_selected":     "bold #8abeb7",
		"project":              "#b294bb",
		"project_selected":     "bold #b294bb",
		"title_selected":       "bold",
		"priority":             "bold #f0c674",
		"priority_selected":    "bold #f0c674",
		"muted":                "#707171",
		"muted_selected":       "#707171",
		"note":                 "#828483",
		"description":          "#828483",
		"link":                 "underline #81a2be",
		"detail_label":         "bold #767777",
		"link_system":          "#8abeb7",
		"error":                "#cc6666",
		"warning":              "#f0c674",
		"due_overdue":          "#cc6666",
		"due_soon":             "#f0c674",
		"due_week":             "#8abeb7",
		"due_far":              "#4c4c4c",
		"due_overdue_selected": "bold #cc6666",
		"due_soon_selected":    "bold #f0c674",
		"due_week_selected":    "bold #8abeb7",
		"due_far_selected":     "#4c4c4c",
		"state_next":           "#8abeb7",
		"state_waiting":        "#f0c674",
		"state_done":           "#4c4c4c",
		"outline_thread":       "#4c4c4c",
	},
	"tomorrow-night-eighties": {
		"tab_active":           "bold #ffffff on-#515151",
		"tab_inactive":         "#7c7c7c",
		"tab_agenda":           "#66cccc",
		"tab_next":             "#99cc99",
		"tab_quadrants":        "#ffcc66",
		"tab_inbox":            "#cc99cc",
		"tab_projects":         "#6699cc",
		"tab_agenda_active":    "bold #66cccc on-#515151",
		"tab_next_active":      "bold #99cc99 on-#515151",
		"tab_quadrants_active": "bold #ffcc66 on-#515151",
		"tab_inbox_active":     "bold #cc99cc on-#515151",
		"tab_projects_active":  "bold #6699cc on-#515151",
		"selection":            "#ffffff on-#515151",
		"accent":               "#66cccc",
		"prompt":               "bold #66cccc",
		"section":              "bold #cccccc",
		"approval_section":     "bold #ffcc66",
		"inbox_section":        "bold #cc99cc",
		"modal_title":          "bold #ffffff on-#515151",
		"border":               "#595959",
		"border_gradient":      "#6699cc #cc99cc @45",
		"form_group_label":     "bold #000000 on-#66cccc",
		"context":              "bold #66cccc",
		"context_selected":     "bold #66cccc",
		"project":              "#cc99cc",
		"project_selected":     "bold #cc99cc",
		"title_selected":       "bold",
		"priority":             "bold #ffcc66",
		"priority_selected":    "bold #ffcc66",
		"muted":                "#7c7c7c",
		"muted_selected":       "#7c7c7c",
		"note":                 "#8d8d8d",
		"description":          "#8d8d8d",
		"link":                 "underline #6699cc",
		"detail_label":         "bold #818181",
		"link_system":          "#66cccc",
		"error":                "#f2777a",
		"warning":              "#ffcc66",
		"due_overdue":          "#f2777a",
		"due_soon":             "#ffcc66",
		"due_week":             "#66cccc",
		"due_far":              "#595959",
		"due_overdue_selected": "bold #f2777a",
		"due_soon_selected":    "bold #ffcc66",
		"due_week_selected":    "bold #66cccc",
		"due_far_selected":     "#595959",
		"state_next":           "#66cccc",
		"state_waiting":        "#ffcc66",
		"state_done":           "#595959",
		"outline_thread":       "#595959",
	},
}
