# The exhaustive Symbol#inspect sweep that found the three defects of the
# 84df4c5 source-fidelity review. Every non-surrogate codepoint is used as an
# unknown constructor keyword, 256 per case, so 1,112,064 names cost 4,344
# cases. `sigil` prefixes each name, which is how the `$`/`@`/`@@` branches of
# query.bareSymbolName are reached.
#
#   ruby generate-symbol-sweep.rb OUT.jsonl [sigil]
#   ruby generate-symbol-sweep.rb OUT.jsonl --digits [max-length]
#
# `$-` is a sigil like any other, which is how the command-line-global rule of
# the 2026-08-02 global-names review is swept rather than sampled: every
# single-codepoint `$-X` name is generated by passing it. The `--digits` mode
# is the second rule from that review — the digit globals, where a leading zero
# decides bare against quoted — and needs its own corpus because it is a sweep
# over digit *strings*, not over codepoints.
#
# Compare structurally, never byte-wise: Ruby's JSON.generate emits U+2028 and
# U+2029 raw where Go's encoder escapes them, for the same decoded value.
require "json"

out = ARGV.fetch(0)
sigil = ARGV.fetch(1, "")

names =
  if sigil == "--digits"
    max_length = Integer(ARGV.fetch(2, "4"))
    (1..max_length).flat_map do |length|
      (0...(10**length)).map { |value| "$" + value.to_s.rjust(length, "0") }
    end
  else
    codepoints = (0..0x10FFFF).reject { |cp| cp >= 0xD800 && cp <= 0xDFFF }
    codepoints.map { |cp| sigil + cp.chr(Encoding::UTF_8) }
  end

File.open(out, "w") do |file|
  names.each_slice(256).with_index do |chunk, index|
    keywords = {}
    chunk.each { |name| keywords[name] = 1 }
    file.puts JSON.generate({ "case_id" => "sym-#{index}", "operation" => "new",
                              "kwargs" => keywords })
  end
end

warn "#{names.length} names in #{(names.length / 256.0).ceil} cases"
