# Emits go/internal/query/inspect_printable.go from an exhaustive Ruby capture
# of String#inspect. A codepoint is "printable" exactly when Ruby renders it
# raw; every other codepoint is escaped. Surrogates cannot exist in a Ruby
# UTF-8 String, so they are absent from the capture and land as non-printable.
#
#   ruby capture-ruby-inspect.rb            # writes ruby-inspect.txt
#   ruby generate-printable-table.rb ruby-inspect.txt > go/internal/query/inspect_printable.go
#
# The capture is ~815k lines and is regenerated, never committed.

capture = ARGV.fetch(0)

escaped = {}
File.foreach(capture) { |line| escaped[line.split("\t", 2).first.to_i] = true }

printable = []
start = nil
(0..0x10FFFF).each do |cp|
  raw = !escaped[cp] && !(cp >= 0xD800 && cp <= 0xDFFF)
  if raw
    start ||= cp
  elsif start
    printable << [start, cp - 1]
    start = nil
  end
end
printable << [start, 0x10FFFF] if start

r16 = printable.select { |_, hi| hi <= 0xFFFF }
r32 = printable.reject { |_, hi| hi <= 0xFFFF }
raise "range straddles the 16-bit boundary" if r32.any? { |lo, _| lo <= 0xFFFF }

rows = lambda do |ranges, width|
  ranges.map { |lo, hi| "\t\t{0x%0*X, 0x%0*X, 1}," % [width, lo, width, hi] }.join("\n")
end

out = []
out << "// Code generated by porting/evidence/query-filter-parse/review-2026-08-02-coercion/generate-printable-table.rb. DO NOT EDIT."
out << ""
out << "package query"
out << ""
out << "import \"unicode\""
out << ""
out << "// rubyPrintable is the set of codepoints Ruby's String#inspect renders raw."
out << "// It is captured from Ruby 4.0.6 rather than expressed with Go's unicode"
out << "// tables for two reasons: the predicate is Onigmo's, not a general-category"
out << "// test (U+00AD, U+200B and U+FEFF print raw while U+0085 and U+2028 do not),"
out << "// and Ruby is on Unicode 17.0.0 while Go's tables are on 15.0.0, which alone"
out << "// moves 148,083 codepoints. Surrogates are absent, so they escape."
out << "var rubyPrintable = &unicode.RangeTable{"
out << "\tR16: []unicode.Range16{"
out << rows.call(r16, 4)
out << "\t},"
out << "\tR32: []unicode.Range32{"
out << rows.call(r32, 6)
out << "\t},"
out << "\tLatinOffset: #{r16.take_while { |_, hi| hi <= 0xFF }.size},"
out << "}"

puts out.join("\n")
