// Ported from Ruby's json gem, ext/json/ext/vendor/fpconv.c, which is itself
// extracted from https://github.com/night-shift/fpconv and modified to append
// ".0" to plain floats. It is Florian Loitsch's Grisu2. Ruby's JSON generator
// calls fpconv_dtoa for every Float, so byte-identical output requires the same
// digit generator: Grisu2 is not always shortest, and strconv is, so 1e23
// spells 9.999999999999999e+22 here and 1e+23 in Go's own formatter.
//
// The port is deliberately transliterated, C shape and all — same variable
// names, same loop structure, same magic numbers — so a reviewer can diff it
// against the C by eye. Do not idiomatize it; it is a fidelity artifact.
//
// Upstream is Boost Software License 1.0:
//
//	Permission is hereby granted, free of charge, to any person or
//	organization obtaining a copy of the software and accompanying
//	documentation covered by this license (the "Software") to use, reproduce,
//	display, distribute, execute, and transmit the Software, and to prepare
//	derivative works of the Software, and to permit third-parties to whom the
//	Software is furnished to do so, all subject to the following:
//
//	The copyright notices in the Software and this entire statement,
//	including the above license grant, this restriction and the following
//	disclaimer, must be included in all copies of the Software, in whole or in
//	part, and all derivative works of the Software, unless such copies or
//	derivative works are solely in the form of machine-executable object code
//	generated by a source language processor.
//
//	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//	DEALINGS IN THE SOFTWARE.

package record

import "math"

const (
	npowers    = 87
	steppowers = 8
	firstpower = -348 // 10 ^ -348

	expmax = -32
	expmin = -60
)

const (
	fracmask  = 0x000FFFFFFFFFFFFF
	expmask   = 0x7FF0000000000000
	hiddenbit = 0x0010000000000000
	signmask  = 0x8000000000000000
	expbias   = 1023 + 52
)

// fp is fpconv's Fp: a fraction and a binary exponent.
type fp struct {
	frac uint64
	exp  int
}

var powersTen = [npowers]fp{
	{18054884314459144840, -1220}, {13451937075301367670, -1193},
	{10022474136428063862, -1166}, {14934650266808366570, -1140},
	{11127181549972568877, -1113}, {16580792590934885855, -1087},
	{12353653155963782858, -1060}, {18408377700990114895, -1034},
	{13715310171984221708, -1007}, {10218702384817765436, -980},
	{15227053142812498563, -954}, {11345038669416679861, -927},
	{16905424996341287883, -901}, {12595523146049147757, -874},
	{9384396036005875287, -847}, {13983839803942852151, -821},
	{10418772551374772303, -794}, {15525180923007089351, -768},
	{11567161174868858868, -741}, {17236413322193710309, -715},
	{12842128665889583758, -688}, {9568131466127621947, -661},
	{14257626930069360058, -635}, {10622759856335341974, -608},
	{15829145694278690180, -582}, {11793632577567316726, -555},
	{17573882009934360870, -529}, {13093562431584567480, -502},
	{9755464219737475723, -475}, {14536774485912137811, -449},
	{10830740992659433045, -422}, {16139061738043178685, -396},
	{12024538023802026127, -369}, {17917957937422433684, -343},
	{13349918974505688015, -316}, {9946464728195732843, -289},
	{14821387422376473014, -263}, {11042794154864902060, -236},
	{16455045573212060422, -210}, {12259964326927110867, -183},
	{18268770466636286478, -157}, {13611294676837538539, -130},
	{10141204801825835212, -103}, {15111572745182864684, -77},
	{11258999068426240000, -50}, {16777216000000000000, -24},
	{12500000000000000000, 3}, {9313225746154785156, 30},
	{13877787807814456755, 56}, {10339757656912845936, 83},
	{15407439555097886824, 109}, {11479437019748901445, 136},
	{17105694144590052135, 162}, {12744735289059618216, 189},
	{9495567745759798747, 216}, {14149498560666738074, 242},
	{10542197943230523224, 269}, {15709099088952724970, 295},
	{11704190886730495818, 322}, {17440603504673385349, 348},
	{12994262207056124023, 375}, {9681479787123295682, 402},
	{14426529090290212157, 428}, {10748601772107342003, 455},
	{16016664761464807395, 481}, {11933345169920330789, 508},
	{17782069995880619868, 534}, {13248674568444952270, 561},
	{9871031767461413346, 588}, {14708983551653345445, 614},
	{10959046745042015199, 641}, {16330252207878254650, 667},
	{12166986024289022870, 694}, {18130221999122236476, 720},
	{13508068024458167312, 747}, {10064294952495520794, 774},
	{14996968138956309548, 800}, {11173611982879273257, 827},
	{16649979327439178909, 853}, {12405201291620119593, 880},
	{9242595204427927429, 907}, {13772540099066387757, 933},
	{10261342003245940623, 960}, {15290591125556738113, 986},
	{11392378155556871081, 1013}, {16975966327722178521, 1039},
	{12648080533535911531, 1066},
}

var tens = [20]uint64{
	10000000000000000000, 1000000000000000000, 100000000000000000,
	10000000000000000, 1000000000000000, 100000000000000,
	10000000000000, 1000000000000, 100000000000,
	10000000000, 1000000000, 100000000,
	10000000, 1000000, 100000,
	10000, 1000, 100,
	10, 1,
}

func absv(n int) int {
	if n < 0 {
		return -n
	}
	return n
}

func minv(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func findCachedPow10(exp int, k *int) fp {
	const oneLogTen = 0.30102999566398114

	approx := int(float64(-(exp + npowers)) * oneLogTen)
	idx := (approx - firstpower) / steppowers

	for {
		current := exp + powersTen[idx].exp + 64

		if current < expmin {
			idx++
			continue
		}

		if current > expmax {
			idx--
			continue
		}

		*k = firstpower + idx*steppowers

		return powersTen[idx]
	}
}

func buildFp(d float64) fp {
	bits := math.Float64bits(d)

	var value fp
	value.frac = bits & fracmask
	value.exp = int((bits & expmask) >> 52)

	if value.exp != 0 {
		value.frac += hiddenbit
		value.exp -= expbias
	} else {
		value.exp = -expbias + 1
	}

	return value
}

func normalize(value *fp) {
	for value.frac&hiddenbit == 0 {
		value.frac <<= 1
		value.exp--
	}

	const shift = 64 - 52 - 1
	value.frac <<= shift
	value.exp -= shift
}

func getNormalizedBoundaries(value *fp, lower, upper *fp) {
	upper.frac = (value.frac << 1) + 1
	upper.exp = value.exp - 1

	for upper.frac&(hiddenbit<<1) == 0 {
		upper.frac <<= 1
		upper.exp--
	}

	const uShift = 64 - 52 - 2

	upper.frac <<= uShift
	upper.exp = upper.exp - uShift

	lShift := 1
	if value.frac == hiddenbit {
		lShift = 2
	}

	lower.frac = (value.frac << lShift) - 1
	lower.exp = value.exp - lShift

	lower.frac <<= lower.exp - upper.exp
	lower.exp = upper.exp
}

func multiply(a, b *fp) fp {
	const lomask = 0x00000000FFFFFFFF

	ahBl := (a.frac >> 32) * (b.frac & lomask)
	alBh := (a.frac & lomask) * (b.frac >> 32)
	alBl := (a.frac & lomask) * (b.frac & lomask)
	ahBh := (a.frac >> 32) * (b.frac >> 32)

	tmp := (ahBl & lomask) + (alBh & lomask) + (alBl >> 32)
	// round up
	tmp += 1 << 31

	return fp{
		frac: ahBh + (ahBl >> 32) + (alBh >> 32) + (tmp >> 32),
		exp:  a.exp + b.exp + 64,
	}
}

func roundDigit(digits []byte, ndigits int, delta, rem, kappa, frac uint64) {
	for rem < frac && delta-rem >= kappa &&
		(rem+kappa < frac || frac-rem > rem+kappa-frac) {

		digits[ndigits-1]--
		rem += kappa
	}
}

func generateDigits(value, upper, lower *fp, digits []byte, K *int) int {
	wfrac := upper.frac - value.frac
	delta := upper.frac - lower.frac

	var one fp
	one.frac = 1 << uint(-upper.exp)
	one.exp = upper.exp

	part1 := upper.frac >> uint(-one.exp)
	part2 := upper.frac & (one.frac - 1)

	idx, kappa := 0, 10
	// 1000000000
	for divp := 10; kappa > 0; divp++ {

		div := tens[divp]
		digit := part1 / div

		if digit != 0 || idx != 0 {
			digits[idx] = byte(digit) + '0'
			idx++
		}

		part1 -= digit * div
		kappa--

		tmp := (part1 << uint(-one.exp)) + part2
		if tmp <= delta {
			*K += kappa
			roundDigit(digits, idx, delta, tmp, div<<uint(-one.exp), wfrac)

			return idx
		}
	}

	// 10
	unit := 18

	for {
		part2 *= 10
		delta *= 10
		kappa--

		digit := part2 >> uint(-one.exp)
		if digit != 0 || idx != 0 {
			digits[idx] = byte(digit) + '0'
			idx++
		}

		part2 &= one.frac - 1
		if part2 < delta {
			*K += kappa
			roundDigit(digits, idx, delta, part2, one.frac, wfrac*tens[unit])

			return idx
		}

		unit--
	}
}

func grisu2(d float64, digits []byte, K *int) int {
	w := buildFp(d)

	var lower, upper fp
	getNormalizedBoundaries(&w, &lower, &upper)

	normalize(&w)

	var k int
	cp := findCachedPow10(upper.exp, &k)

	w = multiply(&w, &cp)
	upper = multiply(&upper, &cp)
	lower = multiply(&lower, &cp)

	lower.frac++
	upper.frac--

	*K = -k

	return generateDigits(&w, &upper, &lower, digits, K)
}

func emitDigits(digits []byte, ndigits int, dest []byte, K int, neg bool) []byte {
	exp := absv(K + ndigits - 1)

	if K >= 0 && exp < 15 {
		dest = append(dest, digits[:ndigits]...)
		for i := 0; i < K; i++ {
			dest = append(dest, '0')
		}

		// add a .0 to mark this as a float.
		return append(dest, '.', '0')
	}

	// write decimal w/o scientific notation
	if K < 0 && (K > -7 || exp < 10) {
		offset := ndigits - absv(K)
		// fp < 1.0 -> write leading zero
		if offset <= 0 {
			offset = -offset
			dest = append(dest, '0', '.')
			for i := 0; i < offset; i++ {
				dest = append(dest, '0')
			}

			return append(dest, digits[:ndigits]...)
		}

		// fp > 1.0
		dest = append(dest, digits[:offset]...)
		dest = append(dest, '.')

		return append(dest, digits[offset:ndigits]...)
	}

	// write decimal w/ scientific notation
	negDigit := 0
	if neg {
		negDigit = 1
	}
	ndigits = minv(ndigits, 18-negDigit)

	dest = append(dest, digits[0])

	if ndigits > 1 {
		dest = append(dest, '.')
		dest = append(dest, digits[1:ndigits]...)
	}

	dest = append(dest, 'e')

	if K+ndigits-1 < 0 {
		dest = append(dest, '-')
	} else {
		dest = append(dest, '+')
	}

	cent := 0

	if exp > 99 {
		cent = exp / 100
		dest = append(dest, byte(cent)+'0')
		exp -= cent * 100
	}
	if exp > 9 {
		dec := exp / 10
		dest = append(dest, byte(dec)+'0')
		exp -= dec * 10
	} else if cent != 0 {
		dest = append(dest, '0')
	}

	return append(dest, byte(exp%10)+'0')
}

// fpconvDtoa is fpconv_dtoa: the spelling Ruby's JSON generator writes for a
// Float. Non-finite values never reach it; encodeNumber refuses them first,
// as Ruby's generator does.
func fpconvDtoa(d float64) string {
	var digits [18]byte

	dest := make([]byte, 0, 32)
	neg := false

	if math.Float64bits(d)&signmask != 0 {
		dest = append(dest, '-')
		neg = true
	}

	if d == 0.0 {
		return string(append(dest, '0', '.', '0'))
	}

	K := 0
	ndigits := grisu2(d, digits[:], &K)

	return string(emitDigits(digits[:], ndigits, dest, K, neg))
}
